name: .NET Core Deploy to IIS

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
      
    - name: Build with dotnet
      run: dotnet build -c Release C:\actions-runner\_work\ASPSelfDeployDemo\ASPSelfDeployDemo\MonSiteASP\MonSiteASP.csproj
    
    - name: dotnet publish
      run: dotnet publish -c Release C:\actions-runner\_work\ASPSelfDeployDemo\ASPSelfDeployDemo\MonSiteASP\MonSiteASP.csproj -o ${{env.DOTNET_ROOT}}\ASPSelfDeployDemo
      
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ${{env.DOTNET_ROOT}}\ASPSelfDeployDemo\* C:\inetpub\wwwroot\asp-self-deploy-demo -Recurse -Force
        iisreset /start

    - name: Curl the website as adopte un dev
      run: curl http://localhost/asp-self-deploy-demo
